activities_index:
    path:     /
    defaults: { _controller: "GameInLyonBundle:Activities:index" }
    methods:  GET

activities_show:
    path:     /{id}/show
    defaults: { _controller: "GameInLyonBundle:Activities:show" }
    methods:  GET

activities_new:
    path:     /new
    defaults: { _controller: "GameInLyonBundle:Activities:new" }
    methods:  [GET, POST]

activities_edit:
    path:     /{id}/edit
    defaults: { _controller: "GameInLyonBundle:Activities:edit" }
    methods:  [GET, POST]

activities_delete:
    path:     /{id}/delete
    defaults: { _controller: "GameInLyonBundle:Activities:delete" }
    methods:  DELETE
