<?php

namespace GameInLyonBundle\Repository;

/**
 * ActivitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
